# Preliminary: Generate Datasets
DATA_SETS:
  SIC:
    SIC_SIZE:     [448,304]
    RANGE:        [1978,2023]
    TRAIN_SPLIT:  [1978,2013]
    VAL_SPLIT:    [2014,2015]
    TEST_SPLIT:   [2016,2023]
    DAILY_DATA_DIR: "/SIC_G02202/Daily"
    MASK_DATA_DIR: "/SIC_G02202/ancillary"
    
    OUTPUT:
      DIR: "/Monthly_Dataset_In6_Pred6"
      

      MULTI_GRANULARITY: True
      MULTI_GRANULARITY_PERIOD: [30] 
      
      # Match Input Horizon and Forecasting Leads
      INPUT_LEN: 6  
      OUTPUT_LEADS: 6  

# Training FM
PRED_FOR_SR:
  # FM_BASE Config
  DATA:
    IMG_SIZE: [448,304] #  H W

  MODEL:
    SWINV2:
      # Adjustable
      WINDOW_SIZE: [28,19] 
      DEPTHS: [ 2, 2, 18, 2 ]
      NUM_HEADS: [ 4, 8, 16, 32 ] 
      
      # Default
      PATCH_SIZE: [2,2] 
      IN_CHANS: 6  
      EMBED_DIM: 32 
      MLP_RATIO: 4.
      OUT_CHANS: 6 
      QKV_BIAS: True
      APE: False
      PATCH_NORM: True
      PRETRAINED_WINDOW_SIZES: [0, 0, 0, 0]
    
    DROP_RATE: 0.0
    NUM_CLASSES: 0

    # Adjustable
    DROP_PATH_RATE: 0.5


  TRAIN:
    RANDOM_SEEDS: 10
    USE_CHECKPOINT: False

    # Pretraining Setup
    EPOCHS: 60 
    WARMUP_EPOCHS: 5
    VAL_PER_EPOCH: 5
    EARLY_STOP_EPOCH: 30 
    BATCH_SIZE: 6 

    NUM_WORKERS: 8
    
    
    SAVE_CKPT_DIR:    "/months/ckpts"
    SAVE_CKPT_PER_BATCH: 10000
    LOGGING_DIR:      "/months/logs"
    TENSOR_BOARD_DIR: "/months/board"
    RECORD_PER_BATCH: 50 
  


    LR_SCHEDULER:
      NAME: "cosine"
      DECAY_EPOCHS: 10 
      DECAY_RATE:   0.1
      WARMUP_PREFIX: True
      GAMMA: 0.1
      MULTISTEPS: []

    OPTIMIZER:
      NAME: 'ADAMW'
      #LR: 1.25e-4
      CLIP_GRAD:    5.0
      MOMENTUM:     0.9
      WEIGHT_DECAY: 0.05
      BASE_LR:      5.e-4 
      WARMUP_LR:    5.e-7 
      MIN_LR:       5.e-6 
      EPSILON:      1.e-8
      BETAS:      [0.9, 0.999]

